version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: openpyxl
    versions:
    - ">= 3.a, < 4"
  - dependency-name: pytest
    versions:
    - "> 6.0.2"
