project = "jchord"
copyright = "2021, Jonathan Reichelt Gjertsen"
author = "Jonathan Reichelt Gjertsen"
extensions = ["sphinx.ext.autodoc"]
templates_path = ["_templates"]
exclude_patterns = ["_build"]
html_theme = "classic"
html_static_path = ["_static"]
html_show_sourcelink = False
