name: Tests
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run tests
        run: |
            pip install -r requirements_dev.txt
            pytest --cov=jchord --cov-report=xml -vvv
      - name: Upload codecov report
        uses: codecov/codecov-action@v2
